### ISSUE TITLE
[PSyIR] use statements not output

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#586]
If a code has a use statement without an only clause, then the use statement is not output by the Fortran backend - at least that is the case for use statements associated with a module.

**Comment by arporter** [comment]
This one may have been fixed by @sergisiso's addition of `ContainerSymbol` (#545)?

**Comment by rupertford** [comment]
#545 goes a long way to fixing this problem but does not fix it. It pulls the container symbols into the symbol table but it does not output them if they are not associated with a data symbol. The Fortran backend needs to be extended to output these (i.e. use statements without an only clause).

For info, if we rewrite the Fortran backend to iterate over container symbols then we could also aggregate symbolts together (i.e. use x, only : y; use x, only : z becomes use x only : y, z).

We may need to iterate over container symbols in any case to ensure that all use statement occur before declarations and before an implicit none, but I am not sure about this.

**Comment by arporter** [comment]
The situation is complicated by the fact that it is perfectly valid Fortran to have, e.g.:

    use my_mod, only: var
    use my_mod
    use my_other_mod, only: var2
    ...

The frontend does not distinguish between the two USEs of `my_mod` and thus the PSyIR currently has no information that the original Fortran looked like this. If we end up with a SymbolTable that contains one or more global symbols with an unresolved interface then we know that (assuming the Fortran is correct) they must be accessed via an un-qualified USE. However, for the example above we have no way of knowing which of the ContainerSymbols (`my_mod` or `my_other_mod`) had such a USE.

**Comment by arporter** [comment]
I think the simplest solution is to catch and reject Fortran of the form given in my example; i.e. for a given module we permit unqualified USE or USE, ONLY but not both in the same scoping unit.

**Comment by arporter** [comment]
We could have a `ContainerSymbol` store a list of the `DataSymbol`s that reference it. If that list is empty then the `ContainerSymbol` must be the subject of an unqualified USE. Possibly we could also have a `None` entry in the list indicate that there is an unqualified USE, this would then permit us to have a qualified USE of the same container in the same scoping unit.

**Comment by rupertford** [comment]
Don't we have 2 concepts here. 1: import a set of symbols from a container and 2: import all public symbols from a container. Clearly for 1: we just want to capture the list (either as a list in a containersymbol or as datasymbols being in a container symbol but for 2: I would explicitly capture this somehow, rather than treat an empty list as meaning all. Capturing it separately would allow for the case where all symbols were implicitly imported as well as some being explicitly imported.

**Comment by rupertford** [comment]
pr #615 adds support for unqualified use statements and it is now on master. Closing this issue.
